import{a as d,i as c,S as g}from"./assets/vendor-YT4DRQk6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const p=d.create({baseURL:"https://pixabay.com/api/",params:{key:"48884243-7c5376715b9f7ca682882ed04",image_type:"photo",orientation:"horizontal",safesearch:"true"}});function f(s){return p.get("",{params:{q:`${s}`}}).then(t=>t.data.hits.length===0?(c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"}),[]):t.data.hits).catch(t=>(c.error({title:"Erorr",messages:"Please try again",titleColor:"white",messageColor:"white",backgroundColor:"red",theme:"dark"}),[]))}const i={gallery:document.querySelector(".js-gallery")};function y(s){u();const t=b(s);i.gallery.innerHTML=t,i.gallery.classList.add("gallery")}function u(){i.gallery.innerHTML=""}function h(s){const{webformatURL:t,largeImageURL:a,tags:l,likes:e,views:r,comments:o,downloads:m}=s;return`<li class="js-gallery-item">
        <a href="${a}">
        <img src="${t}" alt="${l}" width="360" height="158"/>
        </a>
        <ul class="stats">
          <li class="stats-item">Likes<span class="stats-span">${e}</span></li>
          <li class="stats-item">Comments<span class="stats-span">${o}</span></li>
          <li class="stats-item">Views<span class="stats-span">${r}</span></li>
          <li class="stats-item">Downloads<span class="stats-span">${m}</span></li>
        </ul>
      </li>`}function b(s){return s.map(h).join("")}const n={searchForm:document.querySelector(".js-search-form"),loader:document.querySelector(".js-loader"),gallery:document.querySelector(".js-gallery")};n.searchForm.addEventListener("submit",L);function L(s){s.preventDefault(),n.loader.style.display="block";const t=s.target.elements["search-bar"].value;u(),f(t).then(a=>{y(a),w.refresh(),n.loader.style.display="none"}),s.target.reset()}let w=new g(".gallery a");
//# sourceMappingURL=index.js.map
